### ISSUE TITLE
Some generated folders are being saved in parent folder

### ISSUE THREAD

**Issue by rRobis** [niksedk/subtitleedit-avalonia#31]
Some generated folders are being saved in parent folder. 

So if I have Subtitle Edit in C:/SubtitleEdit5  then these folders appear in C:/

Ones that i had:
Waveforms
Spectograms
ShotChanges

(maybe some other?)

**Comment by niksedk** [comment]
Is this fixed in preview-35?
https://github.com/niksedk/subtitleedit-avalonia/releases

**Comment by rRobis** [comment]
They still get created in the parent folder.

I'm on Windows 11, maybe something to do with the path differences between the OS.

**Comment by GrampaWildWilly** [comment]
I reported this in #13 a couple of days ago.  But I now have Preview 36.  I would expect that if things are fixed, I would see the 3 directories still in the directory one level up.  I would expect SE would just put new versions of the directories in the SE directory without deleting the directories from the erroneous location.  But I'm not seeing these 3 directories in my SE directory.  However, I imagine there are only certain actions you might do that would create any of these directories.  I had a Waveforms directory for a few weeks before the ShotChanges & Spectrograms directories got created.  I've never done anything with shot changes nor spectrograms.  I've always just used waveforms.  Now that waveforms are auto-generated, I'm not sure how you get a spectrogram.  In fact, I'm not entirely clear what the difference is between a waveform & a spectrogram.

In any case, I don't have the 3 directories where they belong, only the 3 directories in the incorrect location.  Once I see them where they belong, I expect I will just delete the incorrect ones.  Does this sound like the way to go?  And what exactly will trigger their creation?  I loaded something up into Preview 36 a little while ago that caused a waveform to be auto-generated.  I don't have that in my Waveforms directory that's in the wrong location, & I don't have a new Waveforms directory within my SE directory.  If this issue is fixed, I would have expected that action to have created a new Waveforms directory within the SE directory.  So I'm not so sure this has been fixed, & it might even be a regression.

There is one other issue with these directories.  In fact, it's an issue with all the subdirectories within the SE directory.  In addition, this is true in SE 4, too.  The Windows Properties of all these directories, including the SE directory, shows a property that claims every file inside that directory will be read-only.  In fact, it seems every directory on my system has this property.  I haven't looked at every directory, but several directories on my boot drive created by Windows install have it.  A small random sample of directories on other partitions on my system, directories I created myself, have it.  The files inside these directories are most assuredly not read-only.  So I don't know what effect this folder property is having.  Maybe it's a bug in Windows.  Anyway, it's just something I noticed that I thought was strange.  It apparently isn't really a problem.

**Comment by GrampaWildWilly** [comment]
It seems I have been misinterpreting what I've been seeing.  I entered this query into Google:

There is a property in the Windows Properties for a folder that says, "Read-only (Only applies to files in folder)." This property is enabled on every directory in Windows 11. But none of the files in the directory are read-only. Is this a known bug?

The response from AI was very informative.  The read-only attribute is in fact NOT enabled on my directories.  I needed to put on my reading glasses to see that.  Anyway, run the search yourself & read what it tells you.

In short, never mind.

**Comment by rRobis** [comment]
I tried to run and also publish the app through Rider, and there it creates the folders in the same folder, as expected.

I tested the build 36 some more and the situation is even worse, it doesn't create those folders in parent directory. It just creates it in the top directory of whatever disk you are in C:/. I put it in C:/Testing/Testing/SubtitleEdit.exe and it still creates in C:/ 😄  

I put it in D:/ somewhere deep, and it creates those folders in D:/Waveforms etc

**Comment by niksedk** [comment]
How is preview 38?
https://github.com/niksedk/subtitleedit-avalonia/releases

**Comment by rRobis** [comment]
I was just testing, it's still creating the folders in the C:/ directory

**Comment by niksedk** [comment]
How did you install preview 35? Installer or portable version?

**Comment by rRobis** [comment]
I am using the portable version (i have a script to quickly update it from latest github release). I can try installed version and see what happens

**Comment by GrampaWildWilly** [comment]
Confirmed.  With SE not running I deleted the 3 incorrectly placed directories.  Then I opened SE & reopened a VTT file.  After a few moments the Audio visualizer showed a waveform.  Sure enough, C:\Spectrogram & C:\Waveforms had reappeared.  The former is empty but the latter contains the waveform I had just generated.  I don't have a C:\ShotChanges yet.  What action would cause that to appear?  In any case, this problem appears to be untreated.  This is with the portable SE.  I just unzipped it into C:\Subtitle Edit V5.  Not C:\Program Files\anything, not C:\Tools\whatever.  As I do with all my applications that will permit it, I put SE in its own directory in the root of my C-drive.  I don't have an error_log.txt, despite opening & closing SE a few times.  I thought maybe the file would be written only when SE terminates, but no.  I even checked the root of C-drive.  Not there, either.  But then, I haven't done anything to cause any errors so . . .

**Comment by rRobis** [comment]
Ok when it's installed, then it saves those folders inside.

..........\AppData\Roaming\Subtitle Edit

**Comment by GrampaWildWilly** [comment]
AppData\Roaming?  That's wrong, too.  Those directories should go in the same directory as SubtitleEdit.exe, same as AutoBackup, Dictionaries, Whisper, & all the rest.  Keep it compact.  Don't fling it across my whole partition.  Keep everything in one place so it's easy to find.  Resistance is not futile.  Don't succumb to Microsoft's brain dead recommended way of programming.  Be smarter than them.

**Comment by GrampaWildWilly** [comment]
I don't doubt you're right.  But it's still a stupid way of operating.  SE itself doesn't require any administrator rights.  So there's no good reason to scatter its assets about.  Notepad++ for example explicitly offers an option to avoid using AppData.  There's a smart app.  I want SE to be just as smart.

**Comment by rRobis** [comment]
If i built locally everything right, I think fb29a8f fixed it. It's creating it now in same folder as portable SubtitleEdit.exe

**Comment by GrampaWildWilly** [comment]
Preview 39 looks like it's solved this.  I did as before, deleted the existing Spectrograms, ShotChanges, & Waveforms directories, then opened SE, told it to open a VTT, & let the waveform get generated.  Poof.  I now have an empty Spectrograms directory & a Waveforms directory with that waveform in it, both directories inside my SE directory, where they belong.  +1

I still don't have a ShotChanges directory.  This is not a complaint.  I'm just trying to understand what's going on.  At a certain point, I have had a ShotChanges directory but I don't know what I've done to make it appear.  I let the video I was testing with play for a couple of minutes thinking you have to actually play something for the ShotChanges directory to show up.  But no, that didn't do it.  So I'd like to know what makes that directory appear.

**Comment by niksedk** [comment]
You can generate the shot changes by going into Video - Generate/import shot changes. 
Or you can turn on auto-generate shot changes in settings.
(shot changes will be white vertical lines in the waveform)

**Comment by rRobis** [comment]
@niksedk Hmm yes, i can confirm, that ShotChanges folder still auto generates when opening subtitles. And it's being created in C:/

The Waveforms and Spectograms now create correctly in same directory like SubtitleEdit.exe
